title: Christopher Kang
logo: /assets/img/profile_tall.jpg
description:
show_downloads: false
google_analytics: UA-169623724-1
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax
sass:
  sass_dir: ./_sass
